# Generated by Django 4.2.7 on 2025-05-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('credits', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
